---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: clamav-centos-latest
    image: centos:latest
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        clamav_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: centos-latest
verifier:
  name: goss
  lint:
    name: yamllint
