---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "pRYMRagezO4kzvreBW5PCCqOF05ufjRMXPvIyisBKpxU/u2axjQS3rEwiy/sM/o7nQOEp782kg2k0f3WaQmSe5uUfvmkUhxRnwWo9GlrCv1A8QRqT8f7BeONqLVZ56y8C0zRQwHkhWJY2hmTqtkDVLCD/NHs2si6RdrQ0ZRuCg27uhD5ypBjoNexYnvvBQeOTfjVAxAF7zV+4tqizfQMXVmCy1bd5LKy+MFeePmMMPssP7b77CSn+SN1lLw69pBY0mq8fTFbRCIHch9Z1i03JQW4bmTV5Bg9o2/BONevB6bNO3Ytfv6YBsUveYlZLdJg4VAUS0pg92c3rv+5H/UEgg5suShECRXc2Ql5DyvpETknUUTNiGXMFfWWQr1rd/vK9eA89SQ0/JHg9uNrCuDAOlXaoiUmqSd7iM9K7jwBBzBRFEfh0WQeBoDvYXq/OtXIVYad1fLITsp2zPYPXGyyyys7d+55/FctgFMjZX2M7T9OqdXlJ6vZmSrl1g3R/a7Q3xDXZvsFKVm1g9O0nJ6/CuxwZSmBMbsbpy4aZnwMANV6Daf8yclZzq+vSuppg7ZwYqdwy+OtgFVSaml8vDWWWBi7nWGmLpjcfsdEs4WsInTdt0Ef8NMq8eM8FcXe9yiCq4bgpjGydwdH+svaSkNvospxlw6q0bXEGR7RPERh5bE="
  email: false
