---
- name: test if clamav_can_scan_system is set correctly
  assert:
    that:
      - clamav_can_scan_system is defined
      - clamav_can_scan_system | type_debug == "bool"
    quiet: yes

- name: test if clamav_configuration is set correctly
  assert:
    that:
      - clamav_configuration is defined
      - clamav_configuration | length > 0
      - clamav_configuration is iterable
    quiet: yes

- name: test if item in clamav_configuration is set correctly
  assert:
    that:
      - item.line is defined
      - item.line | length > 0
    quiet: yes
  loop: "{{ clamav_configuration }}"
  loop_control:
    label: "{{ item.line }}"
  when:
    - clamav_configuration is defined

- name: test if item.state in clamav_configuration is set correctly
  assert:
    that:
      - item.state | length > 0
      - item.state in [ "absent", "present" ]
    quiet: yes
  loop: "{{ clamav_configuration }}"
  loop_control:
    label: "{{ item.line }}"
  when:
    - clamav_configuration is defined
    - item.state is defined
