---
# tasks file for clamav
- name: install clamav software
  package:
    name: "{{ clamav_packages }}"
    state: "{{ clamav_package_state }}"
  notify:
    - ensure logfiles exists
    - stop clamav
    - update virus definitions
  register: clamav_install_clamav_software
  until: clamav_install_clamav_software is succeeded
  retries: 3

- name: allowing system virus scanning
  seboolean:
    name: antivirus_can_scan_system
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == "enabled"

- name: allowing jit
  seboolean:
    name: clamd_use_jit
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == "enabled"

- name: install required selinux software
  package:
    name: "{{ clamav_requirements }}"
    state: "{{ clamav_package_state }}"
  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == "enabled"
  register: clamav_install_required_selinux_software
  until: clamav_install_required_selinux_software is succeeded
  retries: 3

- name: place selinux type enforcement
  copy:
    src: my-clamd.te
    dest: /etc/my-clamd.te
  notify:
    - create selinux mod
    - create selinux pp
    - load selinux pp
  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == "enabled"

- name: place freshclam.conf
  template:
    src: freshclam.conf.j2
    dest: "{{ clamav_config_dir }}/freshclam.conf"

- name: create database directory
  file:
    path: "{{ clamav_database_directory }}"
    state: directory

- name: flush handlers
  meta: flush_handlers

- name: configure clamav software
  lineinfile:
    dest: "{{ clamav_config_dir }}/{{ clamav_config_file }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ clamav_configuration }}"
  notify:
    - restart clamav

- name: check update virus definitions
  async_status:
    jid: "{{ updatevirusdefinitions.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 15
  delay: 60
  when:
    - updatevirusdefinitions is defined

- name: start and enable clamav service
  block:
    - name: start and enable software
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      when:
        - ansible_virtualization_type != "docker" or clamav_ignore_docker
      with_items:
        - "{{ clamav_services }}"
  rescue:
    - name: remove selinux type enforcements
      file:
        path: /etc/my-clamd.te
        state: absent
      when:
        - ansible_selinux is defined
        - ansible_selinux
        - ansible_selinux.status == "enabled"
