---
# tasks file for clamav
- name: install clamav software
  package:
    name: "{{ clamav_stable_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default (clamav_stable_packages[ansible_distribution]
          | default (clamav_stable_packages['default'] )) }}"
    state: "{{ clamav_package_state }}"
  notify:
    - update virus definitions
    - ensure logfiles exists

- name: allowing system virus scanning
  seboolean:
    name: antivirus_can_scan_system
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: allowing jit
  seboolean:
    name: clamd_use_jit
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: install required selinux software
  package:
    name: "{{ clamav_requirements }}"
    state: "{{ clamav_package_state }}"
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: place selinux type enforcement
  copy:
    src: my-clamd.te
    dest: /etc/my-clamd.te
  notify:
    - create selinux mod
    - create selinux pp
    - load selinux pp
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: place freshclam.conf
  template:
    src: freshclam.conf.j2
    dest: "{{ clamav_config_dir[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default (clamav_config_dir[ansible_distribution]
          | default (clamav_config_dir['default'] )) }}/freshclam.conf"

- name: create database directory
  file:
    path: "{{ clamav_database_directory }}"
    state: directory

- name: flush handlers
  meta: flush_handlers

- name: configure clamav software
  lineinfile:
    dest: "{{ clamav_config_dir[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default (clamav_config_dir[ansible_distribution]
          | default (clamav_config_dir['default'] )) }}/{{ clamav_config_file[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default (clamav_config_file[ansible_distribution]
          | default (clamav_config_file['default'] )) }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present')}}"
  with_items:
    - "{{ clamav_configuration }}"
  notify:
    - restart clamav

- name: start and enable clamav service
  block:
    - name: start and enable software
      service:
        name: "{{ clamav_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
              | default (clamav_service[ansible_distribution]
              | default (clamav_service['default'] )) }}"
        state: started
        enabled: yes
      when:
        - ansible_virtualization_type != "docker"
  rescue:
    - name: remove selinux type enforcements
      file:
        path: /etc/my-clamd.te
        state: absent
      when:
        - ansible_selinux is defined
        - ansible_selinux != false
        - ansible_selinux.status == "enabled"
