---
# tasks file for clamav
- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ clamav_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(clamav_packages[ansible_distribution]
      | default(clamav_packages['default'] )) }}"
  notify:
    - update virus definitions
    - ensure logfile exists

- name: allowing system virus scanning
  seboolean:
    name: antivirus_can_scan_system
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: allowing jit
  seboolean:
    name: clamd_use_jit
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: install required selinux software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ clamav_extra_software[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(clamav_extra_software[ansible_distribution]
      | default(clamav_extra_software['default'] )) }}"
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: place selinux type enforcement
  copy:
    src: my-clamd.te
    dest: /etc/my-clamd.te
  notify:
    - create selinux mod
    - create selinux pp
    - load selinux pp
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: flush handlers
  meta: flush_handlers

- name: configure software
  lineinfile:
    dest: "{{ clamav_config[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(clamav_config[ansible_distribution]
      | default(clamav_config['default'] )) }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present')}}"
  with_items:
    - "{{ clamav_configuration }}"
  notify:
    - restart clamav

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ clamav_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(clamav_services[ansible_distribution]
      | default(clamav_services['default'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
