---
# tasks file for clamav
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ clamav_packages }}"
  notify:
    - update virus definitions
    - ensure logfile exists

- name: allowing system virus scanning
  seboolean:
    name: antivirus_can_scan_system
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: allowing jit
  seboolean:
    name: clamd_use_jit
    state: yes
    persistent: yes
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: install required selinux software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ clamav_requirements }}"
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: place selinux type enforcement
  copy:
    src: my-clamd.te
    dest: /etc/my-clamd.te
  notify:
    - create selinux mod
    - create selinux pp
    - load selinux pp
  when:
    - ansible_selinux is defined
    - ansible_selinux != false
    - ansible_selinux.status == "enabled"

- name: place freshclam.conf
  template:
    src: freshclam.conf.j2
    dest: "{{ clamav_config_dir }}/freshclam.conf"

- name: flush handlers
  meta: flush_handlers

- name: configure software
  lineinfile:
    dest: "{{ clamav_config_dir }}/{{ clamav_config_file }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present')}}"
  with_items:
    - "{{ clamav_configuration }}"
  notify:
    - restart clamav

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ clamav_service }}"
  when:
    - ansible_virtualization_type != "docker"
