---
# handlers file for clamav
- name: restart clamav
  service:
    name: "{{ clamav_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
          | default (clamav_service[ansible_distribution]
          | default (clamav_service['default'] )) }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: ensure logfiles exists
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ clamav_owner[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
           | default (clamav_owner[ansible_distribution]
           | default (clamav_owner['default'] )) }}"
    group: "{{ clamav_group[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
           | default (clamav_group[ansible_distribution]
           | default (clamav_group['default'] )) }}"
  with_items:
    - /var/log/clamd.scan
    - "{{ clamav_freshclam_log_dir[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default (clamav_freshclam_log_dir[ansible_distribution]
      | default (clamav_freshclam_log_dir['default'] )) }}/freshclam.log"

- name: update virus definitions
  command: freshclam
  async: 900
  poll: 60
  register: updatevirusdefinitions
  notify:
    - check update virus definitions

- name: check update virus definitions
  async_status:
    jid: "{{ updatevirusdefinitions.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 15
  delay: 60

- name: create selinux mod
  command: checkmodule -M -m -o /etc/my-clamd.mod /etc/my-clamd.te

- name: create selinux pp
  command: semodule_package -o /etc/my-clamd.pp -m /etc/my-clamd.mod

- name: load selinux pp
  command: semodule -i /etc/my-clamd.pp
