---
# handlers file for clamav
- name: restart software
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ clamav_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(clamav_services[ansible_distribution]
      | default(clamav_services['default'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
