---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: clamav-centos-6
    box: centos/6
  - name: clamav-centos-7
    box: centos/7
  - name: clamav-debian-jessie64
    box: debian/jessie64
  - name: clamav-debian-buster64
    box: desc/buster64
  - name: clamav-fedora-26-cloud-base
    box: fedora/26-cloud-base
  - name: clamav-fedora-27-cloud-base
    box: fedora/27-cloud-base
  - name: clamav-opensuse-openSUSE-42-2-x86-64
    box: opensuse/openSUSE-42.2-x86_64
  - name: clamav-ubuntu-trusty
    box: elastic/ubuntu-14.04-x86_64
  - name: clamav-ubuntu-artful
    box: generic/ubuntu1710
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    # - destroy
verifier:
  name: goss
  lint:
    name: 'None'
