---
# vars file for clamav
clamav_packages:
  - clamav
  - clamav-scanner
  - clamav-scanner-systemd
  - clamav-update

clamav_config_dir: /etc/clamd.d
clamav_config_file: scan.conf

clamav_freshclam_log_dir: /var/log/clamav

clamav_service: clamav

clamav_owner: clamav
clamav_group: clamav

clamav_requirements:
  - checkpolicy
  - policycoreutils-python
  - policycoreutils
