---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: clamav-debian-sid
    image: debian:sid
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: debian-sid
